{{- if .Values.azureIdentity.enabled }}
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: {{ .Values.azureIdentity.name }}
  namespace: {{ template "aad-pod-identity.azureidentity.namespace" . }}
  labels:
    {{- include "aad-pod-identity.labels" . | nindent 4 }}
spec:
  type: {{ .Values.azureIdentity.type }}
  resourceID: {{ required ".Values.azureIdentity.resourceID is required!" .Values.azureIdentity.resourceID }}
  clientID: {{ required ".Values.azureIdentity.clientID is required!" .Values.azureIdentity.clientID }}
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: {{ .Values.azureIdentityBinding.name }}
  namespace: {{ template "aad-pod-identity.azureidentitybinding.namespace" . }}
  labels:
    {{- include "aad-pod-identity.labels" . | nindent 4 }}
spec:
  azureIdentity: {{ .Values.azureIdentity.name }}
  selector: {{ required ".Values.azureIdentityBinding.selector is required!" .Values.azureIdentityBinding.selector }}
{{- end }}
