{{- if not (empty .Values.azureIdentities) -}}
apiVersion: v1
kind: List
items:
{{- range $key, $value := .Values.azureIdentities }}
  - apiVersion: "aadpodidentity.k8s.io/v1"
    kind: AzureIdentity
    metadata:
      name: {{ default $key $value.name }}
      namespace: {{ default $.Release.Namespace $value.namespace }}
      labels:
        {{- include "aad-pod-identity.labels" $ | nindent 8 }}
    spec:
      type: {{ $value.type }}
      clientID: {{ required "clientID is required!" $value.clientID }}
      {{- if eq (int $value.type) 0 }}
      resourceID: {{ required "resourceID is required!" $value.resourceID }}
      {{- else }}
      tenantID: {{ required "tenantID is required!" $value.tenantID }}
      clientPassword: {{ required "clientPassword is required!" $value.clientPassword }}
      auxiliaryTenantIDs:
        {{- range $value.auxiliaryTenantIDs }}
        - {{ . }}
        {{- end }}
      {{- end }}
  - apiVersion: "aadpodidentity.k8s.io/v1"
    kind: AzureIdentityBinding
    metadata:
      name: {{ $value.binding.name }}
      namespace: {{ default $.Release.Namespace $value.namespace }}
      labels:
        {{- include "aad-pod-identity.labels" $ | nindent 8 }}
    spec:
      azureIdentity: {{ default $key $value.name }}
      selector: {{ required "binding.selector is required!" $value.binding.selector }}
{{- end }}
{{- end -}}
