{{- if .Values.azureIdentity.enabled }}
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
 name: {{ .Values.azureIdentity.name }}
spec:
 type: {{ .Values.azureIdentity.type }}
 ResourceID: {{required ".Values.azureIdentity.resourceID is required!" .Values.azureIdentity.resourceID }}
 ClientID: {{required ".Values.azureIdentity.clientID is required!" .Values.azureIdentity.clientID }}
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
 name: {{ .Values.azureIdentityBinding.name }}
spec:
 AzureIdentity: {{ .Values.azureIdentity.name }}
 Selector: {{required ".Values.azureIdentityBinding.selector is required!" .Values.azureIdentityBinding.selector }}
{{- end }}