apiVersion: v1
kind: List
items:
{{- range .Values.azureIdentities }}
  - apiVersion: "aadpodidentity.k8s.io/v1"
    kind: AzureIdentity
    metadata:
      name: {{ .name }}
      namespace: {{ default $.Release.Namespace .namespace }}
      labels:
        app.kubernetes.io/name: {{ template "aad-pod-identity.name" $ }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app.kubernetes.io/managed-by: {{ $.Release.Service }}
        helm.sh/chart: {{ template "aad-pod-identity.chart" $ }}
    spec:
      type: {{ .type }}
      ResourceID: {{ required "resourceID is required!" .resourceID }}
      ClientID: {{ required "clientID is required!" .clientID }}
  - apiVersion: "aadpodidentity.k8s.io/v1"
    kind: AzureIdentityBinding
    metadata:
      name: {{ .binding.name }}
      namespace: {{ default $.Release.Namespace .namespace }}
      labels:
        app.kubernetes.io/name: {{ template "aad-pod-identity.name" $ }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app.kubernetes.io/managed-by: {{ $.Release.Service }}
        helm.sh/chart: {{ template "aad-pod-identity.chart" $ }}
    spec:
      AzureIdentity: {{ .name }}
      Selector: {{ required "binding.selector is required!" .binding.selector }}
{{- end }}
