{{- if .Values.rbac.pspEnabled }}
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ template "aad-pod-identity-psp.mic.fullname" . }}
  labels:
  {{- include "aad-pod-identity.labels" . | nindent 4 }}
spec:
  privileged: false
  allowPrivilegeEscalation: false
  fsGroup:
    ranges:
      - max: 65535
        min: 1
    rule: MustRunAs
  supplementalGroups:
    ranges:
      - max: 65535
        min: 1
    rule: MustRunAs
  requiredDropCapabilities:
    - ALL
  volumes:
    - hostPath
    - secret
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  {{- end }}
