apiVersion: v2
description: Deploy components for aad-pod-identity
name: aad-pod-identity
version: 3.0.3
appVersion: 1.7.4
home: https://github.com/Azure/aad-pod-identity
sources:
  - https://github.com/Azure/aad-pod-identity
maintainers:
  - name: aramase
    email: anish.ramasekar@gmail.com
