apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
 name: demo-aad1
spec:
 type: 0
 ResourceID: /subscriptions/c1089427-83d3-4286-9f35-5af546a6eb67/resourcegroups/MC_nbhatia-eu-01_eu-1_eastus/providers/Microsoft.ManagedIdentity/userAssignedIdentities/demo-aad1
 ClientID: 89f69b3d-5b41-4b14-afbf-18fd96104e14