# See https://github.com/golangci/golangci-lint#config-file
run:
  issues-exit-code: 1 # default
  tests: true # default
  go: "1.19"

linters:
  enable:
    - misspell
    - goimports
    - golint
    - gofmt
    - gosec

linters-settings:
  misspell:
    locale: US
  goimports:
    local-prefixes: github.com/Azure/aad-pod-identity

issues:
  exclude:
  - G114
  - SA4023
  - SA1019
