# See https://github.com/golangci/golangci-lint#config-file
run:
  issues-exit-code: 1 # default
  tests: true # default

linters:
  enable:
    - misspell
    - goimports
    - golint
    - gofmt
    - gosec

linters-settings:
  misspell:
    locale: US
  goimports:
    local-prefixes: github.com/Azure/aad-pod-identity
