# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - docs/*

pr:
  branches:
    include:
    - master
  paths:
    exclude:
    - docs/*

pool:
 vmImage: 'ubuntu-latest'

steps:
- task: GoTool@0
  inputs:
    version: '1.14.1'
- script:  make build
  displayName: 'Build'
- script: |
   make unit-test
  displayName: 'Run tests'
- script: |
   make helm-lint
  displayName: 'Run helm lint'
