apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: azure-service-principal
spec:
  type: 1
##resourceID: RESOURCE_ID
  clientID: "X23b7685-XXXX-XXXX-XXXX-9c0b63bc28fX"
  tenantID: "X367c01e-XXXX-XXXX-XXXX-cfc2beb7264X"
  clientPassword:
    name: "azdevsecret"
    namespace: "default"
---
apiVersion: v1
kind: Secret
metadata:
  name: azdevsecret
type: Opaque
stringData:
    clientSecret: "TO...................K4kq......1LR"
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: azure-service-principal-binding
spec:
  azureIdentity: azure-service-principal
  selector: azure-service-principal-pod
