{{- if (index .Values "aad-pod-identity").enabled -}}
{{- $apiVersion := "apiextensions.k8s.io/v1beta1" -}}
{{- if .Capabilities.APIVersions.Has "apiextensions.k8s.io/v1" -}}
{{- $apiVersion = "apiextensions.k8s.io/v1" -}}
{{- end }}
apiVersion: {{ $apiVersion | quote }}
kind: CustomResourceDefinition
metadata:
  name: azureassignedidentities.aadpodidentity.k8s.io
  annotations:
    "helm.sh/hook": crd-install
  labels:
    app.kubernetes.io/name: aad-pod-identity
    app.kubernetes.io/instance: aad-pod-identity
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: aad-pod-identity
spec:
  group: aadpodidentity.k8s.io
  {{- if eq $apiVersion "apiextensions.k8s.io/v1beta1" }}
  version: v1
  {{- else }}
  versions:
  - name: v1
    served: true
    storage: true
  {{- end }}
  names:
    kind: AzureAssignedIdentity
    plural: azureassignedidentities
  scope: Namespaced
---
apiVersion: {{ $apiVersion | quote }}
kind: CustomResourceDefinition
metadata:
  name: azureidentitybindings.aadpodidentity.k8s.io
  annotations:
    "helm.sh/hook": crd-install
  labels:
    app.kubernetes.io/name: aad-pod-identity
    app.kubernetes.io/instance: aad-pod-identity
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: aad-pod-identity
spec:
  group: aadpodidentity.k8s.io
  {{- if eq $apiVersion "apiextensions.k8s.io/v1beta1" }}
  version: v1
  {{- else }}
  versions:
  - name: v1
    served: true
    storage: true
  {{- end }}
  names:
    kind: AzureIdentityBinding
    plural: azureidentitybindings
  scope: Namespaced
---
apiVersion: {{ $apiVersion | quote }}
kind: CustomResourceDefinition
metadata:
  name: azureidentities.aadpodidentity.k8s.io
  annotations:
    "helm.sh/hook": crd-install
  labels:
    app.kubernetes.io/name: aad-pod-identity
    app.kubernetes.io/instance: aad-pod-identity
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: aad-pod-identity
spec:
  group: aadpodidentity.k8s.io
  {{- if eq $apiVersion "apiextensions.k8s.io/v1beta1" }}
  version: v1
  {{- else }}
  versions:
  - name: v1
    served: true
    storage: true
  {{- end }}
  names:
    kind: AzureIdentity
    singular: azureidentity
    plural: azureidentities
  scope: Namespaced
---
apiVersion: {{ $apiVersion | quote }}
kind: CustomResourceDefinition
metadata:
  name: azurepodidentityexceptions.aadpodidentity.k8s.io
  annotations:
    "helm.sh/hook": crd-install
  labels:
    app.kubernetes.io/name: aad-pod-identity
    app.kubernetes.io/instance: aad-pod-identity
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: aad-pod-identity
spec:
  group: aadpodidentity.k8s.io
  {{- if eq $apiVersion "apiextensions.k8s.io/v1beta1" }}
  version: v1
  {{- else }}
  versions:
  - name: v1
    served: true
    storage: true
  {{- end }}
  names:
    kind: AzurePodIdentityException
    singular: azurepodidentityexception
    plural: azurepodidentityexceptions
  scope: Namespaced
