{{- if .Values.mic.podDisruptionBudget }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: mic-pdb
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: {{ .Values.mic.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/component: mic
{{- end }}
