{{- if .Values.installMICException }}
{{- if eq .Values.operationMode "standard"}}
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzurePodIdentityException
metadata:
  name: mic
  namespace: {{ .Release.Namespace }}
spec:
  podLabels:
    app: mic
    component: mic
    app.kubernetes.io/component: mic
---
{{- end}}
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzurePodIdentityException
metadata:
  name: aks-addon-exception
  namespace: kube-system
spec:
  podLabels:
    kubernetes.azure.com/managedby: aks
{{- end }}
