{{- if .Values.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ template "aad-pod-identity.nmi.fullname" . }}
  labels:
    {{- include "aad-pod-identity.labels" . | nindent 4 }}
    app.kubernetes.io/component: nmi
subjects:
- kind: ServiceAccount
  name: {{ template "aad-pod-identity.nmi.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "aad-pod-identity.nmi.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
