apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
 name: client-principal-binding
spec:
 AzureIdentity: client-principal
 Selector:  
  aadpodidbinding: client-principal-pod-binding