apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
 name: client-principal
spec:
 type: 0
 ResourceID: <resource-id of client-principal>
 ClientID: <client-id of client-principal>