apiVersion: v1
kind: Service
metadata:
  name: aad-id-service
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: aad-id-service
---
apiVersion: v1
kind: Pod
metadata:
  name: aad-id-service-pod
  labels:
    app: aad-id-service
    platform: csharp
spec:
  containers:
  - name: api-container
    image: vplauzon/aad-pod-id-svc
    env:
    - name: TENANT_ID
      value: 72f988bf-86f1-41af-91ab-2d7cd011db47
    - name: APPLICATION_ID
      value: https://vault.azure.net
