apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demo
    aadpodidbinding: demo
  name: demo
  namespace: default
spec:
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
        aadpodidbinding: demo
    spec:
      containers:
      - name: demo
        image: "mcr.microsoft.com/oss/azure/aad-pod-identity/demo:v1.7.5"
        imagePullPolicy: Always
        args:
          - "--subscriptionid=SUBSCRIPTION_ID"
          - "--clientid=CLIENT_ID"
          - "--resourcegroup=RESOURCE_GROUP"
      nodeSelector:
        kubernetes.io/os: linux
