apiVersion: v1
kind: Pod
metadata:
  name: test-client-pod
  labels:
    app: cli-test-client
    aadpodidbinding:  little-pod-binding
spec:
  containers:
  - name: main-container
    image: vplauzon/aad-pod-id-client
    env:
    - name: RESOURCE
      value: https://vault.azure.net
    - name: SERVICE_URL
      value: http://test-svc-pod
