jobs:
  - job: unit_test
    timeoutInMinutes: 20
    cancelTimeoutInMinutes: 5
    workspace:
      clean: all
    steps:
      - script: make unit-test
        displayName: Run unit tests
      - script: bash <(curl -s https://codecov.io/bash) -C $(Build.SourceVersion)
        displayName: Upload coverage to codecov
      - script: make lint
        displayName: Run lint
      - script: make helm-lint
        displayName: Run helm lint
      - template: scan-images.yml
