apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - aadpodidentity.k8s.io_azureassignedidentities.yaml
  - aadpodidentity.k8s.io_azureidentities.yaml
  - aadpodidentity.k8s.io_azureidentitybindings.yaml
  - aadpodidentity.k8s.io_azurepodidentityexceptions.yaml
patchesStrategicMerge:
  - annotations.yaml
