trigger: none

schedules:
  - cron: "0 0 * * *"
    always: true
    displayName: "Nightly Build & Test"
    branches:
      include:
        - master

pool: Upstream Pool

jobs:
  - template: templates/unit-test.yml
  - template: templates/e2e-test.yml
    parameters:
      clusterConfigs:
        - "aks"
        # File names in test/e2e/cluster_configs without file extension
        - "vmss"
        - "vmas"
  - template: templates/soak-test.yml
    parameters:
      clusterConfigs:
        - "pi-vmas-e2e-daily"
        - "pi-vmss-e2e-daily"
        - "pi-aks-e2e-daily"
  - template: templates/load-test.yml
    parameters:
      operationModes:
        - "managed"
        - "standard"
