trigger: none

schedules:
  - cron: "0 0 * * *"
    always: true
    displayName: "Nightly Build & Test"
    branches:
      include:
        - master

pool: staging-pool

jobs:
  - template: templates/unit-test.yml
  - template: templates/e2e-test.yml
    parameters:
      clusterConfigs:
        - "aks"
  - template: templates/soak-test.yml
    parameters:
      clusterConfigs:
        - "pi-aks-e2e-daily"
  - template: templates/load-test.yml
    parameters:
      operationModes:
        - "managed"
        - "standard"
