jobs:
  - job: unit_tests
    timeoutInMinutes: 20
    cancelTimeoutInMinutes: 5
    workspace:
      clean: all
    steps:
      - task: GoTool@0
        inputs:
          version: 1.15
      - script: make build
        displayName: Build
      - script: make unit-test
        displayName: Run unit tests
      - script: bash <(curl -s https://codecov.io/bash)
        displayName: Upload coverage to codecov
        env:
          CODECOV_TOKEN: $(CODECOV_TOKEN)
      - script: make lint
        displayName: Run lint
      - script: make helm-lint
        displayName: Run helm lint
